name: movie_admin
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# flutter packages pub run build_runner build --delete-conflicting-outputs
# (\w+):(\s+)([a-zA-Z\s\[\]|]+);
# $3 get $1;

dependencies:
  qr_code_scanner: ^0.1.0
  charts_flutter: ^0.9.0
  built_value: ^7.1.0
  octo_image: ^0.3.0
  uuid: ^2.2.2
  distinct_value_connectable_stream: 1.2.0-beta02
  built_collection: ^4.3.2
  flutter_slidable: ^0.5.7
  url_launcher: ^5.7.2
  expandable: ^4.1.4
  meta: ^1.2.3
  flutter_rating_bar: ^3.2.0+1
  rx_redux: ^2.1.1
  stream_loader: ^1.1.0-beta02
  loading_indicator: ^1.2.0
  google_sign_in: ^4.5.6
  font_awesome_flutter: ^8.10.0
  image_picker: ^0.6.7+11
  cached_network_image: ^2.4.1
  firebase_storage: ^5.1.0
  flutter_dotenv: ^2.1.0
  flutter_google_places: 0.2.6
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  tuple: ^1.0.3
  rxdart: ^0.25.0
  flutter_bloc_pattern: ^1.2.0
  flutter_disposebag: ^1.0.0
  disposebag: ^1.4.0
  flutter_provider: ^1.1.1
  http: ^0.12.2
  rx_shared_preferences: ^1.3.4
  firebase_auth: ^0.18.3+1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: 1.10.2
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  rxdart: 0.25.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

